### ISSUE TITLE
Battery voltage doesn't change across many days? Library Version 1.1.0

### ISSUE THREAD

**Issue by matiasandina** [KravitzLabDevices/FED3_library#26]
Just found this issue of battery voltage not changing?
It looked like my FEDs were fine on battery but one died after 4 days. Last battery recording is 4.25, which happens to be the recording across the whole experiment?
It seems like this device died because it was clogged but still curious about the battery logging not going down at all (experiment lasted ~72 h) and battery is constant for other FEDs on the same experiment. 

![image](https://user-images.githubusercontent.com/7494967/107823683-29bc1200-6d4e-11eb-861e-8839e1299c14.png)

I have not tried this on Library Version > 1.1.0, I just updated all my FEDs to 1.2.5 but might need to fix this again :grimacing: ?

**Comment by KravitzLab** [comment]
Good catch!  Sorry about that somewhere I dropped reading the battery voltage while it was running.  It should be fixed, can you try updating to 1.2.6 and confirm?
