### ISSUE TITLE
Add argument to Feed() to enable or disable pulse

### ISSUE THREAD

**Issue by AlexLM96** [KravitzLabDevices/FED3_library#35]

**Comment by KravitzLab** [comment]
Instead of enable/disable, make it an Int to send a user-settable number of pulses

**Comment by KravitzLab** [comment]
Also add arguments for:
- Pulses at pellet retrieval
- Boolean for whether to wait for pellet retrieval or not

**Comment by KravitzLab** [comment]
Done in v1.16.0
